// Fails (non-zero exit) if the committed option-library-fallback.json is
// stale relative to the committed src/data/option-library/*.ts source
// files — i.e. someone edited a category file and forgot to re-run
// `npm run gen:option-library-fallback` before committing.
//
// Compares a content hash, not file mtimes, since mtimes don't survive git
// checkouts, zip extraction, or CI/Windows consistently.
//
// This does NOT touch the database — it only checks that the committed
// snapshot matches the committed source files, so it's safe to run in any
// CI job (PR checks, pre-commit) without DB credentials. The actual build
// (`npm run build`) regenerates the snapshot fresh from the DB regardless;
// this check exists to catch staleness in contexts where that doesn't run.
//
// Usage: npx tsx scripts/check-option-library-fallback-fresh.ts

import fs from "fs"
import path from "path"
import { hashOptionLibrarySource } from "./generate-option-library-fallback"

const SNAPSHOT_PATH = path.join(__dirname, "../src/data/option-library-fallback.json")

function main() {
  if (!fs.existsSync(SNAPSHOT_PATH)) {
    console.error(`${SNAPSHOT_PATH} does not exist. Run: npm run gen:option-library-fallback`)
    process.exit(1)
  }

  const snapshot = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf8"))
  const committedHash = snapshot.sourceHash as string | undefined
  const currentHash = hashOptionLibrarySource()

  if (!committedHash) {
    console.error("Snapshot has no sourceHash — it predates this check, or was generated by an old version of the script. Run: npm run gen:option-library-fallback")
    process.exit(1)
  }

  if (committedHash !== currentHash) {
    console.error(
      "option-library-fallback.json is stale: src/data/option-library/*.ts has changed since the snapshot was last generated.\n" +
      "Run: npm run gen:option-library-fallback\n" +
      `  snapshot hash: ${committedHash}\n` +
      `  current hash:  ${currentHash}`
    )
    process.exit(1)
  }

  console.log("option-library-fallback.json is fresh.")
}

main()
